[changelog]
header = """
# Changelog\n
"""

body = """
{% if version %}\
	## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
	## [unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
	{% if group | striptags | trim == "Dependencies" %}
		{% if not loop.first %}<br/>{% endif %}

		**Dependency Updates:** \
		{% for commit in commits %}\
			[{{ loop.index }}\
			{% if not loop.last %},{% endif %}\
			](https://github.com/ottomated/create-o7-app/commit/{{ commit.id }})\
			{% if not loop.last %} {% endif %}\
		{% endfor %}
	{% else %}
	### {{ group | striptags | trim }}
		{% for commit in commits %}
			- {% if commit.scope %}*({{ commit.scope }})* {% endif %}\
			{% if commit.breaking %}[**breaking**] {% endif %}\
			{{ commit.message }}
		{% endfor %}	
	{% endif %}
{% endfor %}\n
"""
# template for the changelog footer
footer = """
{% if releases | length == 1 %}
	### See the [full changelog](https://github.com/ottomated/create-o7-app/blob/main/CHANGELOG.md)
{% endif %}
<!-- generated by git-cliff -->
"""
# remove the leading and trailing s
trim = true
# postprocessors
postprocessors = [
	# { pattern = '<REPO>', replace = "https://github.com/orhun/git-cliff" }, # replace repository URL
]

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
# regex for preprocessing the commit messages
commit_preprocessors = []
# regex for parsing and grouping commits
commit_parsers = [
	{ message = "^feat", group = "<!-- 0 -->features" },
	{ message = "^fix", group = "<!-- 1 -->fixes" },
	{ message = "^refactor", group = "<!-- 2 -->refactor" },
	{ message = "^doc", group = "<!-- 3 -->docs" },
	{ message = "^perf", group = "<!-- 4 -->performance" },
	{ message = "^chore\\(release\\): prepare for", skip = true },
	{ message = "^chore: Release", skip = true },
	{ message = "^ci: Update changelog", skip = true },
	{ message = "^chore\\(deps.*\\)", skip = true },
	{ message = "^chore\\(pr\\)", skip = true },
	{ message = "^chore\\(pull\\)", skip = true },
	{ message = "^ci: Update dependencies", group = "<!-- 6 -->Dependencies" },
	{ message = "^chore|^ci", group = "<!-- 5 -->misc" },
]
protect_breaking_commits = false
filter_commits = false
topo_order = false
sort_commits = "oldest"
