name: Test
on:
  pull_request:

jobs:
  generate-features:
    runs-on: ubuntu-latest
    outputs:
      features: ${{ steps.generate-features.outputs.features }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Generate features
        id: generate-features
        run: cargo run --bin generate-features >> "$GITHUB_OUTPUT"
  
  test:
    needs: generate-features
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: ${{ fromJson(needs.generate-features.outputs.features) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install pnpm
        run: npm i -g pnpm
      - name: Save features to file
        run: echo "${{ matrix.features }}" > features.txt
      - name: Run test
        run: cargo test --test integration_test

